#---------------- CA OE1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ca
  name: ca
  namespace: org1
spec:
  type: ClusterIP
  ports:
  - name: "https"
    port: 7054
    targetPort: 7054
  selector:
    app: ca
