--- #---------------- Orderer0 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer4
  name: orderer4
  namespace: consortium
spec:
  type: ClusterIP
  ports:
    - name: "orderer"
      port: 7050
      targetPort: 7050
  selector:
    app: orderer4
---
#---------------- Orderer2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer4
    metrics-service: "true"
  name: orderer4-metrics
  namespace: consortium
spec:
  type: ClusterIP
  ports:
    - name: "orderer-metrics"
      port: 8443
      targetPort: 8443
  selector:
    app: orderer4
