--- #---------------- Orderer0 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer3
  name: orderer3
  namespace: consortium
spec:
  type: ClusterIP
  ports:
    - name: "orderer"
      port: 7050
      targetPort: 7050
  selector:
    app: orderer3
---
#---------------- Orderer2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer3
    metrics-service: "true"
  name: orderer3-metrics
  namespace: consortium
spec:
  type: ClusterIP
  ports:
    - name: "orderer-metrics"
      port: 8443
      targetPort: 8443
  selector:
    app: orderer3
