--- #---------------- Peer1 org2 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer1
  name: peer1
  namespace: org2
spec:
  type: ClusterIP
  ports:
    - name: "peer-core"
      port: 7051
      targetPort: 7051
  selector:
    app: peer1
---
#---------------- Peer1 org2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer1
    metrics-service: "true"
  name: peer1-metrics
  namespace: org2
spec:
  type: ClusterIP
  ports:
    - name: "peer-metrics"
      port: 9443
      targetPort: 9443
  selector:
    app: peer1
